# Generated by Django 3.1.7 on 2021-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_price', models.IntegerField(blank=True, null=True)),
                ('discount_price', models.CharField(max_length=100)),
                ('beginning_price_rub', models.DecimalField(decimal_places=7, max_digits=20)),
                ('beginning_price_btc', models.DecimalField(decimal_places=7, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена в рублях')),
                ('final_price_btc', models.DecimalField(decimal_places=9, default=0, max_digits=9, verbose_name='Общая цена в btc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
