# Generated by Django 3.1.7 on 2021-05-12 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
        ('products', '0002_auto_20210512_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracker',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='usertracker',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='tracker.TrackedProduct'),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='tracker.usertracker', verbose_name='UserTracker'),
        ),
    ]
