# Generated by Django 3.1.7 on 2021-03-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория магазина', 'verbose_name_plural': 'Категории магазинов'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='shopdescription',
            options={'verbose_name': 'Описание магазина', 'verbose_name_plural': 'Описание магазинов'},
        ),
    ]
